### ISSUE TITLE
希望能得到一点代码复现的帮助

### ISSUE THREAD

**Issue by wayneHallway** [Riwei-HEU/DENS#1]
您好，我是一个偶然间看见你论文的读者，您的论文写的很好，我在尝试弄懂您论文的同时很好奇您是如何复现srns的，凭我自己的力量很难在您现在的数据集上复现srns，可不可以请您帮助我一下

**Comment by Riwei-HEU** [comment]
您好，感谢您的关注，关于SRNS的复现工作你可以联系这篇文章的三作 Zhao Yuhan (asa9ao@hrbeu.edu.cn)，他帮助我复现了SRNS的代码。同时，他本人也有一篇一作的负采样工作发表在RecSys 2023上，在Recbole框架上实现了SRNS。你可以在 https://github.com/Asa9aoTK/ANS-Recbole 中给他评论，如果有其他问题欢迎随时问我，谢谢！

**Comment by 1364301688** [comment]
这是来自QQ邮箱的自动回复邮件。你好，您的邮件已收到！

**Comment by 1364301688** [comment]
> 您好，感谢您的关注，关于SRNS的复现工作你可以联系这篇文章的三作 Zhao Yuhan ([asa9ao@hrbeu.edu.cn](mailto:asa9ao@hrbeu.edu.cn))，他帮助我复现了SRNS的代码。同时，他本人也有一篇一作的负采样工作发表在RecSys 2023上，在Recbole框架上实现了SRNS。你可以在 https://github.com/Asa9aoTK/ANS-Recbole 中给他评论，如果有其他问题欢迎随时问我，谢谢！

**Comment by wayneHallway** [comment]
感谢您

**Comment by wayneHallway** [comment]
这是来自QQ邮箱的自动回复邮件。你好，您的邮件已收到！
